#!/usr/bin/env bash

PROJECT_NAME="${PROJECT_NAME:-protein_ligand_md}"
PIPELINE_DIR="${PIPELINE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
INPUT_DIR="${INPUT_DIR:-${PIPELINE_DIR}/inputs}"
WORK_DIR="${WORK_DIR:-${PIPELINE_DIR}/work}"
RESULTS_DIR="${RESULTS_DIR:-${PIPELINE_DIR}/results}"
LOG_DIR="${LOG_DIR:-${PIPELINE_DIR}/logs}"
STATE_DIR="${STATE_DIR:-${PIPELINE_DIR}/state}"
ANALYSIS_DIR="${ANALYSIS_DIR:-${PIPELINE_DIR}/analysis}"
TMP_DIR="${TMP_DIR:-${PIPELINE_DIR}/tmp}"

PROTEIN_PDB="${PROTEIN_PDB:-${INPUT_DIR}/protein.pdb}"
LIGAND_INPUT="${LIGAND_INPUT:-${INPUT_DIR}/ligand.mol2}"
LIGAND_INPUT_FORMAT="${LIGAND_INPUT_FORMAT:-mol2}"
DOCKING_COMPLEX_PDB="${DOCKING_COMPLEX_PDB:-}"
DOCKING_LIGAND_RESNAME="${DOCKING_LIGAND_RESNAME:-}"

GMX_BIN="${GMX_BIN:-gmx}"
MPI_LAUNCHER="${MPI_LAUNCHER:-}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
OBABEL_BIN="${OBABEL_BIN:-obabel}"
ACPYPE_BIN="${ACPYPE_BIN:-acpype}"
CGENFF_BIN="${CGENFF_BIN:-cgenff}"
CGENFF_CONVERTER="${CGENFF_CONVERTER:-${PIPELINE_DIR}/cgenff_charmm2gmx_py3_nx3.py}"
CGENFF_PYTHON="${CGENFF_PYTHON:-${PYTHON_BIN}}"

FORCE_FIELD="${FORCE_FIELD:-amber99sb-ildn}"
WATER_MODEL="${WATER_MODEL:-tip3p}"
LIGAND_PREP_TOOL="${LIGAND_PREP_TOOL:-acpype}"
AUTO_RECTIFY="${AUTO_RECTIFY:-yes}"
ACPYPE_ATOMTYPE="${ACPYPE_ATOMTYPE:-gaff2}"
CGENFF_FORCEFIELD_DIR="${CGENFF_FORCEFIELD_DIR:-${PIPELINE_DIR}/${FORCE_FIELD}.ff}"

LIGAND_NAME="${LIGAND_NAME:-ligand}"
LIGAND_RESNAME="${LIGAND_RESNAME:-LIG}"
LIGAND_NET_CHARGE="${LIGAND_NET_CHARGE:-0}"
PROTEIN_MOLECULE_NAME="${PROTEIN_MOLECULE_NAME:-Protein_chain_A}"
LIGAND_MOLECULE_NAME="${LIGAND_MOLECULE_NAME:-${LIGAND_RESNAME}}"
STRIP_HETATM="${STRIP_HETATM:-yes}"
PREPARED_LIGAND_ITP="${PREPARED_LIGAND_ITP:-}"
PREPARED_LIGAND_GRO="${PREPARED_LIGAND_GRO:-}"
PREPARED_LIGAND_POSRE="${PREPARED_LIGAND_POSRE:-}"
PREPARED_LIGAND_PRM="${PREPARED_LIGAND_PRM:-}"

BOX_TYPE="${BOX_TYPE:-dodecahedron}"
BOX_DISTANCE_NM="${BOX_DISTANCE_NM:-1.0}"
ION_CONCENTRATION_M="${ION_CONCENTRATION_M:-0.15}"
POSRES_FC="${POSRES_FC:-1000 1000 1000}"

TEMPERATURE_K="${TEMPERATURE_K:-300}"
PRESSURE_BAR="${PRESSURE_BAR:-1.0}"
EM_STEPS="${EM_STEPS:-50000}"
NVT_TIME_PS="${NVT_TIME_PS:-1000}"
NPT_TIME_PS="${NPT_TIME_PS:-1000}"
NVT_STEPS="${NVT_STEPS:-}"
NPT_STEPS="${NPT_STEPS:-}"
MD_TIME_NS="${MD_TIME_NS:-100}"
TIMESTEP_PS="${TIMESTEP_PS:-0.002}"
# Production replicas share the prepared NPT structure but receive separate,
# deterministic velocity seeds. Keep this at 1 for the historical single-run mode.
ENSEMBLE_REPLICAS="${ENSEMBLE_REPLICAS:-1}"
ENSEMBLE_BASE_SEED="${ENSEMBLE_BASE_SEED:-20260903}"
# validate: refuse a corrupt checkpoint; required: also refuse a missing one;
# off: never resume from a checkpoint.
CHECKPOINT_POLICY="${CHECKPOINT_POLICY:-validate}"
CHECKPOINT_INTERVAL_MIN="${CHECKPOINT_INTERVAL_MIN:-15}"

GMX_MAXWARN="${GMX_MAXWARN:-0}"
USE_GPU="${USE_GPU:-auto}"
GPU_ID="${GPU_ID:-}"
PIN_THREADS="${PIN_THREADS:-on}"
NTMPI="${NTMPI:-1}"
# "auto" uses the CPU allocation visible to this job (including cgroup limits).
# A positive integer remains available when a machine-specific override is needed.
NTOMP="${NTOMP:-auto}"

ANALYSIS_FIT_GROUP="${ANALYSIS_FIT_GROUP:-Backbone}"
ANALYSIS_RMS_GROUP="${ANALYSIS_RMS_GROUP:-Protein}"
ANALYSIS_LIGAND_GROUP="${ANALYSIS_LIGAND_GROUP:-Ligand}"
RUN_RESULT_ANALYSIS="${RUN_RESULT_ANALYSIS:-yes}"
RUN_FREE_ENERGY="${RUN_FREE_ENERGY:-no}"
RUN_UMBRELLA="${RUN_UMBRELLA:-no}"
RUN_MMBSA="${RUN_MMBSA:-yes}"
FREE_ENERGY_SELECTION="${FREE_ENERGY_SELECTION:-backbone}"
FREE_ENERGY_TEMPERATURE_K="${FREE_ENERGY_TEMPERATURE_K:-${TEMPERATURE_K}}"
FREE_ENERGY_COMPONENTS="${FREE_ENERGY_COMPONENTS:-3}"
FREE_ENERGY_BINS="${FREE_ENERGY_BINS:-180}"
FREE_ENERGY_FRAME_STEP="${FREE_ENERGY_FRAME_STEP:-1}"
MD_CENTER_NOJUMP="${MD_CENTER_NOJUMP:-yes}"
MD_CENTER_GROUP="${MD_CENTER_GROUP:-Protein_Ligand}"
MD_CENTER_OUTPUT_GROUP="${MD_CENTER_OUTPUT_GROUP:-System}"

MMBSA_FRAME_STEP="${MMBSA_FRAME_STEP:-10}"
MMBSA_IONIC_STRENGTH="${MMBSA_IONIC_STRENGTH:-0.15}"
MMBSA_DECOMPOSE="${MMBSA_DECOMPOSE:-no}"
MMBSA_USE_APBS="${MMBSA_USE_APBS:-yes}"
MMBSA_SURFACE_TENSION="${MMBSA_SURFACE_TENSION:-0.0072}"

EM_MDP="${EM_MDP:-${PIPELINE_DIR}/mdp/em.mdp}"
IONS_MDP="${IONS_MDP:-${PIPELINE_DIR}/mdp/ions.mdp}"
NVT_MDP="${NVT_MDP:-${PIPELINE_DIR}/mdp/nvt.mdp}"
NPT_MDP="${NPT_MDP:-${PIPELINE_DIR}/mdp/npt.mdp}"
MD_MDP="${MD_MDP:-${PIPELINE_DIR}/mdp/md.mdp}"
# The bundled CHARMM port has a broken automatic N-terminal MET block. These
# menu selections choose standard NH3+ (1) and COO- (0) termini with pdb2gmx.
CHARMM_N_TERMINUS_SELECTION="${CHARMM_N_TERMINUS_SELECTION:-1}"
CHARMM_C_TERMINUS_SELECTION="${CHARMM_C_TERMINUS_SELECTION:-0}"

