#!/usr/bin/env bash

set -Eeuo pipefail

export LC_ALL=C

prepare_directories() {
  mkdir -p \
    "${INPUT_DIR}" \
    "${WORK_DIR}" \
    "${RESULTS_DIR}" \
    "${LOG_DIR}" \
    "${STATE_DIR}" \
    "${ANALYSIS_DIR}" \
    "${TMP_DIR}"
}

runtime_override_file() {
  printf '%s/auto_rectification.env' "${STATE_DIR}"
}

load_runtime_overrides() {
  local override_file
  override_file="$(runtime_override_file)"
  if [[ -f "${override_file}" ]]; then
    # shellcheck disable=SC1090
    source "${override_file}"
  fi
}

auto_rectify_config() {
  case "${AUTO_RECTIFY:-yes}" in
    yes|true|1|auto)
      prepare_directories
      export PIPELINE_DIR FORCE_FIELD WATER_MODEL LIGAND_PREP_TOOL AUTO_RECTIFY GMXLIB
      "${PYTHON_BIN}" "${PIPELINE_DIR}/helpers/auto_rectify_config.py" "$(runtime_override_file)" >/dev/null
      load_runtime_overrides
      ;;
    no|false|0)
      ;;
    *)
      die "AUTO_RECTIFY must be yes or no"
      ;;
  esac
}

configure_acpype_runtime_environment() {
  # ACPYPE's bundled AmberTools programs are native executables. When ACPYPE
  # is installed with Conda, their HDF libraries live in that Python prefix.
  # Keep that library path scoped to ACPYPE; exporting it globally can make
  # system GROMACS load Conda's older libstdc++.
  local python_prefix library_dir
  ACPYPE_LIBRARY_DIR=""
  python_prefix="$("${PYTHON_BIN}" -c 'import sys; print(sys.prefix)' 2>/dev/null || true)"
  library_dir="${python_prefix}/lib"
  [[ -d "${library_dir}" ]] || return 0

  ACPYPE_LIBRARY_DIR="${library_dir}"
}

acpype_cmd() {
  # ACPYPE's native AmberTools programs inherit this environment, while the
  # rest of the workflow continues to use the system runtime.
  if [[ -n "${ACPYPE_LIBRARY_DIR:-}" && -d "${ACPYPE_LIBRARY_DIR}" ]]; then
    env "LD_LIBRARY_PATH=${ACPYPE_LIBRARY_DIR}" "$@"
  else
    env -u LD_LIBRARY_PATH "$@"
  fi
}

run_acpype_preflight() {
  acpype_cmd "${PYTHON_BIN}" "${PIPELINE_DIR}/helpers/check_acpype_runtime.py" "$@"
}

run_acpype_cmd() {
  # Log ACPYPE invocations consistently while providing AmberTools with the
  # Conda libraries required by its bundled native executables.
  log "CMD: $*"
  acpype_cmd "$@"
}

auto_select_ligand_generator() {
  # This runs before protein topology generation because CGenFF and ACPYPE
  # require different force-field families.
  case "${AUTO_RECTIFY:-yes}" in
    yes|true|1|auto)
      ;;
    no|false|0)
      return 0
      ;;
    *)
      die "AUTO_RECTIFY must be yes or no"
      ;;
  esac

  load_runtime_overrides
  [[ "${LIGAND_PREP_TOOL}" == "cgenff" ]] || return 0

  local cgenff_executable acpype_executable
  read -r cgenff_executable _ <<< "${CGENFF_BIN}"
  if command -v "${cgenff_executable}" >/dev/null 2>&1; then
    return 0
  fi

  read -r acpype_executable _ <<< "${ACPYPE_BIN}"
  if ! command -v "${acpype_executable}" >/dev/null 2>&1; then
    die "CGenFF command '${cgenff_executable}' is not available, and ACPYPE fallback is also unavailable. Install CGenFF, or install ACPYPE and run 'bash ${PIPELINE_DIR}/setup_ubuntu.sh'."
  fi

  configure_acpype_runtime_environment
  if ! run_acpype_preflight --require-detected "${ACPYPE_BIN}"; then
    die "CGenFF command '${cgenff_executable}' is not available and ACPYPE cannot run. Run 'bash ${PIPELINE_DIR}/setup_ubuntu.sh', then restart the job."
  fi

  log "CGenFF command '${cgenff_executable}' was not found; automatically switching to ACPYPE with a compatible AMBER force field."
  persist_runtime_override LIGAND_PREP_TOOL acpype
  auto_rectify_config
}

preflight_ligand_runtime() {
  # Verify native ligand tooling before pdb2gmx creates any partial job files.
  load_runtime_overrides
  case "${LIGAND_PREP_TOOL}" in
    acpype)
      require_command "${ACPYPE_BIN}"
      configure_acpype_runtime_environment
      if ! run_acpype_preflight --require-detected "${ACPYPE_BIN}"; then
        die "ACPYPE cannot run in its current environment. Run 'bash ${PIPELINE_DIR}/setup_ubuntu.sh', then restart the job."
      fi
      ;;
    cgenff)
      require_command "${CGENFF_BIN}"
      require_command "${CGENFF_PYTHON}"
      require_file "${CGENFF_CONVERTER}"
      ;;
    prepared_topology|pypolybuilder)
      ;;
    *)
      die "Unsupported LIGAND_PREP_TOOL: ${LIGAND_PREP_TOOL}"
      ;;
  esac
}

persist_runtime_override() {
  local key="$1"
  local value="$2"
  local override_file
  override_file="$(runtime_override_file)"
  mkdir -p "${STATE_DIR}"
  if [[ -f "${override_file}" ]]; then
    grep -v "^export ${key}=" "${override_file}" > "${override_file}.tmp" || true
    mv "${override_file}.tmp" "${override_file}"
  else
    printf '# Generated by the MD auto-rectification layer\n' > "${override_file}"
  fi
  printf 'export %s=%q\n' "${key}" "${value}" >> "${override_file}"
  export "${key}=${value}"
}

log() {
  printf '[%s] %s\n' "$(date '+%F %T')" "$*"
}

die() {
  log "ERROR: $*"
  exit 1
}

require_file() {
  local file="$1"
  [[ -f "${file}" ]] || die "Required file not found: ${file}"
}

require_command() {
  local command_name="$1"
  local executable
  read -r executable _ <<< "${command_name}"
  command -v "${executable}" >/dev/null 2>&1 || die "Required command not found in PATH: ${executable}"
}

step_stamp() {
  local step_name="$1"
  printf '%s/%s.done' "${STATE_DIR}" "${step_name}"
}

step_should_run() {
  local step_name="$1"
  if [[ "${FORCE:-0}" == "1" ]]; then
    return 0
  fi
  [[ ! -f "$(step_stamp "${step_name}")" ]]
}

mark_step_done() {
  local step_name="$1"
  date '+%F %T' > "$(step_stamp "${step_name}")"
}

init_step_logging() {
  local step_name="$1"
  mkdir -p "${LOG_DIR}"
  CURRENT_LOG="${LOG_DIR}/${step_name}.log"
  exec > >(tee -a "${CURRENT_LOG}") 2>&1
  trap 'die "Step failed at line ${LINENO}. Check ${CURRENT_LOG}"' ERR
  log "Starting ${step_name}"
}

run_cmd() {
  log "CMD: $*"
  "$@"
}

gmx_cmd() {
  local gmx_executable
  local -a mpi_args
  read -r gmx_executable _ <<< "${GMX_BIN}"
  # The Ubuntu GROMACS executable must use its system libstdc++, not one
  # injected by an activated Conda/Anaconda environment for ACPYPE.
  if [[ -n "${MPI_LAUNCHER}" ]]; then
    read -r -a mpi_args <<< "${MPI_LAUNCHER}"
    env -u LD_LIBRARY_PATH "${mpi_args[@]}" "${gmx_executable}" "$@"
  else
    env -u LD_LIBRARY_PATH "${gmx_executable}" "$@"
  fi
}

detect_gromacs_version() {
  local version_text
  version_text="$(gmx_cmd --version 2>/dev/null | awk -F: '/GROMACS version/ {gsub(/^[ \t]+/, "", $2); print $2; exit}')"
  echo "${version_text:-unknown}"
}

solvent_box_for_water_model() {
  local model
  model="$(printf '%s' "${WATER_MODEL}" | tr '[:upper:]' '[:lower:]')"
  case "${model}" in
    spc|spce|tip3p|tip3p_original)
      printf 'spc216.gro\n'
      ;;
    tip4p|tip4pew)
      printf 'tip4p.gro\n'
      ;;
    tip5p)
      printf 'tip5p.gro\n'
      ;;
    *)
      printf '%s.gro\n' "${model}"
      ;;
  esac
}

detect_gpu_flags() {
  local flags=()
  local mdrun_help
  mdrun_help="$(gmx_cmd mdrun -h 2>&1 || true)"

  case "${USE_GPU}" in
    yes)
      ;;
    no)
      echo ""
      return 0
      ;;
    auto)
      if ! command -v nvidia-smi >/dev/null 2>&1; then
        echo ""
        return 0
      fi
      ;;
    *)
      die "USE_GPU must be one of: auto, yes, no"
      ;;
  esac

  # The GPU-related mdrun options are listed even by CPU-only GROMACS builds.
  # Do not rely on nvidia-smi alone: a host can expose an NVIDIA driver while
  # the selected gmx binary was compiled without CUDA, SYCL, HIP, or OpenCL.
  if ! gmx_cmd --version 2>/dev/null | awk -F: '
    /^GPU support:/ {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); exit tolower($2) ~ /^(disabled|none|no)$/}
  '; then
    log "GROMACS GPU support is unavailable; running mdrun on CPU." >&2
    echo ""
    return 0
  fi

  [[ "${mdrun_help}" == *"-nb"* ]] && flags+=(-nb gpu)
  [[ "${mdrun_help}" == *"-pme"* ]] && flags+=(-pme gpu)
  [[ "${mdrun_help}" == *"-bonded"* ]] && flags+=(-bonded gpu)

  if [[ -n "${GPU_ID}" ]]; then
    flags+=(-gpu_id "${GPU_ID}")
  fi

  printf '%s\n' "${flags[*]}"
}

effective_cpu_threads() {
  # nproc honours scheduler CPU affinity and cpusets. Cap it at an explicit
  # cgroup CPU quota too, which nproc does not report on every platform.
  local threads quota period quota_threads
  threads="$(nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)"
  [[ "${threads}" =~ ^[1-9][0-9]*$ ]] || threads=1

  if [[ -r /sys/fs/cgroup/cpu.max ]]; then
    read -r quota period < /sys/fs/cgroup/cpu.max || true
  elif [[ -r /sys/fs/cgroup/cpu/cpu.cfs_quota_us && -r /sys/fs/cgroup/cpu/cpu.cfs_period_us ]]; then
    quota="$(< /sys/fs/cgroup/cpu/cpu.cfs_quota_us)"
    period="$(< /sys/fs/cgroup/cpu/cpu.cfs_period_us)"
  fi
  if [[ "${quota:-max}" =~ ^[1-9][0-9]*$ && "${period:-}" =~ ^[1-9][0-9]*$ ]]; then
    quota_threads=$(( (quota + period - 1) / period ))
    (( quota_threads < threads )) && threads="${quota_threads}"
  fi
  printf '%s\n' "${threads}"
}

resolve_ntomp() {
  case "${NTOMP}" in
    auto|0|"") effective_cpu_threads ;;
    *)
      [[ "${NTOMP}" =~ ^[1-9][0-9]*$ ]] || die "NTOMP must be 'auto' or a positive integer"
      printf '%s\n' "${NTOMP}"
      ;;
  esac
}

checkpoint_is_valid() { local checkpoint="$1"; [[ -s "${checkpoint}" ]] && gmx_cmd dump -cp "${checkpoint}" >/dev/null 2>&1; }
production_primary_dir() { if [[ "${ENSEMBLE_REPLICAS:-1}" == "1" ]]; then printf '%s/production\n' "${RESULTS_DIR}"; else printf '%s/production/replica_001\n' "${RESULTS_DIR}"; fi; }
build_mdrun_args() {
  local deffnm="$1"
  local gpu_flags ntomp
  gpu_flags="$(detect_gpu_flags)"
  ntomp="$(resolve_ntomp)"
  local args=(-deffnm "${deffnm}" -pin "${PIN_THREADS}")
  if [[ "${NTMPI}" != "0" ]]; then
    args+=(-ntmpi "${NTMPI}")
  fi
  args+=(-ntomp "${ntomp}")
  if [[ -f "${deffnm}.cpt" ]]; then
    if [[ "${CHECKPOINT_POLICY:-validate}" != "off" ]]; then
      if checkpoint_is_valid "${deffnm}.cpt"; then args+=(-cpi "${deffnm}.cpt" -noappend)
      elif [[ -s "${deffnm}.cpt" ]]; then printf 'Checkpoint validation failed: %s\n' "${deffnm}.cpt" >&2; return 1
      else printf 'Ignoring empty initial checkpoint: %s\n' "${deffnm}.cpt" >&2; fi
    fi
  fi
  if [[ "${CHECKPOINT_INTERVAL_MIN:-15}" != "0" ]]; then
    args+=(-cpt "${CHECKPOINT_INTERVAL_MIN}")
  fi
  if [[ -n "${gpu_flags}" ]]; then
    read -r -a gpu_args <<< "${gpu_flags}"
    args+=("${gpu_args[@]}")
  fi
  printf '%s\n' "${args[*]}"
}

run_mdrun_with_fallback() {
  # If a GPU-capable build still fails when GPU tasks are selected (for
  # example, a driver/device assignment error), retry the same TPR once on
  # CPU. A CPU failure is allowed to propagate normally so real simulation
  # errors are not hidden.
  local deffnm="$1"
  local -a mdrun_args cpu_args
  local mdrun_args_text
  if ! mdrun_args_text="$(build_mdrun_args "${deffnm}")"; then
    die "Refusing to run with an invalid checkpoint for ${deffnm}."
  fi
  read -r -a mdrun_args <<< "${mdrun_args_text}"
  log "mdrun CPU threads: ${NTOMP} (effective: $(resolve_ntomp)); GPU mode: ${USE_GPU}"

  if gmx_cmd mdrun "${mdrun_args[@]}"; then
    return 0
  fi

  if [[ " ${mdrun_args[*]} " != *" -nb gpu "* ]]; then
    return 1
  fi

  cpu_args=()
  local index=0
  while (( index < ${#mdrun_args[@]} )); do
    case "${mdrun_args[index]}" in
      -nb|-pme|-bonded|-gpu_id)
        ((index += 2))
        ;;
      *)
        cpu_args+=("${mdrun_args[index]}")
        ((index += 1))
        ;;
    esac
  done

  log "GPU mdrun failed; retrying once on CPU with the same run input."
  gmx_cmd mdrun "${cpu_args[@]}"
}

ensure_forcefield_compatibility() {
  load_runtime_overrides
  case "${LIGAND_PREP_TOOL}" in
    acpype)
      [[ "${FORCE_FIELD}" == amber* || "${FORCE_FIELD}" == charmm* ]] || die "LIGAND_PREP_TOOL=acpype requires an AMBER or CHARMM-family force field when AUTO_RECTIFY=no."
      ;;
    cgenff)
      [[ "${FORCE_FIELD}" == charmm* ]] || die "LIGAND_PREP_TOOL=${LIGAND_PREP_TOOL} requires a CHARMM-family force field."
      ;;
    pypolybuilder)
      [[ "${FORCE_FIELD}" == gromos* ]] || log "Warning: pyPolyBuilder is most commonly used with GROMOS-style building-block parameters."
      ;;
    atb)
      # ATB supports GROMOS, AMBER, CHARMM, and OPLS
      ;;
    prepared_topology)
      log "Using the force field referenced by the supplied topology."
      ;;
    *)
      die "Unsupported LIGAND_PREP_TOOL: ${LIGAND_PREP_TOOL}"
      ;;
  esac
}

render_mdp() {
  local template="$1"
  local output="$2"
  require_file "${template}"
  export TEMPERATURE_K PRESSURE_BAR POSRES_FC
  export MD_CONTINUATION MD_GEN_VEL MD_GEN_SEED
  export EM_STEPS NVT_TIME_PS NPT_TIME_PS NVT_STEPS NPT_STEPS MD_TIME_NS MD_STEPS TIMESTEP_PS
  "${PYTHON_BIN}" "${PIPELINE_DIR}/helpers/render_mdp.py" "${template}" "${output}"
}

make_protein_ligand_index() {
  local structure_file="$1"
  local index_file="$2"
  require_file "${structure_file}"
  log "CMD: ${GMX_BIN} make_ndx -f ${structure_file} -o ${index_file}"
  printf 'name 12 Ligand\n1 | 12\nq\n' | gmx_cmd make_ndx -f "${structure_file}" -o "${index_file}"
}

print_runtime_summary() {
  load_runtime_overrides
  log "Project: ${PROJECT_NAME}"
  log "GROMACS: ${GMX_BIN} ($(detect_gromacs_version))"
  log "Force field: ${FORCE_FIELD}"
  log "Water model: ${WATER_MODEL}"
  log "Ligand preparation: ${LIGAND_PREP_TOOL}"
  log "Auto rectification: ${AUTO_RECTIFY}"
  log "Protein input: ${PROTEIN_PDB}"
  log "Ligand input: ${LIGAND_INPUT}"
}

extract_moleculetype_name() {
  local itp_file="$1"
  awk '
    /^\[ moleculetype \]/ {flag=1; next}
    flag && $0 ~ /^[[:space:]]*;/ {next}
    flag && NF > 0 {print $1; exit}
  ' "${itp_file}"
}

load_runtime_overrides
